# -*- coding: utf-8 -*-
"""streamlit code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-_mBZHYhj5B9tOhztnnQaYGoWY9f8PFO
"""

# Install dependencies (run this once in your environment)
# !pip install streamlit PyPDF2 nltk sentence-transformers faiss-cpu transformers

import streamlit as st
import PyPDF2
import nltk
from nltk.tokenize import sent_tokenize
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import json
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

# Download nltk data once
nltk.download('punkt')

# ---------- Load and preprocess PDF once ----------
@st.cache_data(show_spinner=True)
def load_and_preprocess(pdf_path):
    pdf_reader = PyPDF2.PdfReader(open(pdf_path, "rb"))
    all_text = []
    for page in pdf_reader.pages:
        text = page.extract_text()
        if text:
            all_text.append(text)
    full_text = "\n".join(all_text)

    raw_chunks = full_text.split('\n\n')
    final_chunks = []
    for raw_chunk in raw_chunks:
        sentences = sent_tokenize(raw_chunk)
        if len(sentences) <= 5:
            final_chunks.append(raw_chunk.strip())
        else:
            for i in range(0, len(sentences), 3):
                chunk = " ".join(sentences[i:i+3]).strip()
                final_chunks.append(chunk)

    return final_chunks

# ---------- Create embeddings and FAISS index ----------
@st.cache_data(show_spinner=True)
def create_faiss_index(chunks):
    embed_model = SentenceTransformer('all-MiniLM-L6-v2')
    chunk_embeddings = embed_model.encode(chunks, show_progress_bar=True)

    dimension = chunk_embeddings.shape[1]
    index = faiss.IndexFlatL2(dimension)
    index.add(chunk_embeddings)
    return embed_model, index, chunk_embeddings

# ---------- Load LLM model ----------
@st.cache_resource(show_spinner=True)
def load_llm_model():
    model_name = "google/flan-t5-large"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
    generator = pipeline("text2text-generation", model=model, tokenizer=tokenizer)
    return generator

# ---------- Retrieval function ----------
def search_similar_chunks(query, embed_model, index, chunks, k=5):
    query_embedding = embed_model.encode([query])
    distances, indices = index.search(query_embedding, k)
    results = []
    for i in indices[0]:
        results.append({
            "chunk": chunks[i],
            "chunk_id": int(i)  # convert numpy.int64 to int for safety
        })
    return results

# ---------- Generate answer ----------
def generate_answer_with_llm(query, retrieved_chunks, generator, student_level="weak"):
    tone = (
        "Explain clearly and in detail, as if teaching a Class 9 student, using simple language and examples."
    )
    context = "\n".join(chunk["chunk"] for chunk in retrieved_chunks)

    prompt = (
        f"Read the following context carefully and answer the question clearly.\n\n"
        f"Context:\n{context}\n\n"
        f"Question: {query}\n"
        f"{tone}\n"
        f"Answer in detail, using examples and explanations. Write a paragraph or more.\n"
        f"Answer:"
    )

    response = generator(
        prompt,
        max_new_tokens=256,
        do_sample=False,
        num_beams=4,
        early_stopping=True
    )
    answer = response[0]['generated_text']
    if "Answer:" in answer:
        answer = answer.split("Answer:")[-1].strip()
    return answer

# ---------- Logging function ----------
def log_interaction(user_id, student_level, query, retrieved_chunks, answer, log_file="interaction_log.jsonl"):
    safe_chunks = []
    for chunk in retrieved_chunks:
        safe_chunk = chunk.copy()
        if isinstance(safe_chunk.get("chunk_id"), (np.integer,)):
            safe_chunk["chunk_id"] = int(safe_chunk["chunk_id"])
        safe_chunks.append(safe_chunk)
    log_entry = {
        "user_id": user_id,
        "student_level": student_level,
        "query": query,
        "retrieved_chunks": safe_chunks,
        "answer": answer
    }
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(json.dumps(log_entry) + "\n")

# --------- Streamlit UI ---------
def main():
    st.title("Class 9 Science Q&A Chatbot")

    # Load your PDF data, embedding model and FAISS index once
    pdf_path = "class9_science_combined.pdf"  # Update this path accordingly
    chunks = load_and_preprocess(pdf_path)
    embed_model, index, chunk_embeddings = create_faiss_index(chunks)
    generator = load_llm_model()

    student_level = st.selectbox("Select Student Level:", ["weak", "strong"])
    query = st.text_input("Enter your question:")

    if st.button("Get Answer") and query.strip() != "":
        with st.spinner("Searching and generating answer..."):
            top_chunks = search_similar_chunks(query, embed_model, index, chunks, k=5)
            answer = generate_answer_with_llm(query, top_chunks, generator, student_level)

            st.subheader("Retrieved Context Chunks:")
            for i, chunk in enumerate(top_chunks, 1):
                st.markdown(f"**Chunk #{i}:** {chunk['chunk']}")

            st.subheader("Chatbot Answer:")
            st.write(answer)

            # Log the interaction (you can customize user_id as needed)
            log_interaction(
                user_id="student_1",
                student_level=student_level,
                query=query,
                retrieved_chunks=top_chunks,
                answer=answer
            )

if __name__ == "__main__":
    main()